version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml

      - type: bind
        source: ./targets.json
        target: /targets.json
    command: ["--config.file=/config.yaml"]

  ddfexporter:
    build: ./
    ports:
      - 9170:9170

    environment:
      BIND_PORT: 9170
      HOST_ADDRESS: "https://10.0.75.1"
      HOST_PORT: 8993
      METRIC_PREFIX: "ddf_"
      METRIC_API_LOCATION: "services/internal/metrics"
      SECURE: "False"

    volumes:
      - type: bind
        source: ./cacert.pem
        target: /cacerts/cert.pem

